### ISSUE TITLE
Make detailed information more accessible on mobile

### ISSUE THREAD

**Issue by TylerADavis** [paramshah10/VA-dashboard#3]
On the desktop version of the dashboard, it's clear that the white tiles at the top of the screen are just quick insights into trends, and the rest of the information is immediately visible below. 

On mobile however, the initial view consists solely of these white tiles, and it's not clear that more detailed information is available. When we shared these screenshots with the broader mobile-sensing group, some people were wondering where the detailed information had gone. Some proposed solutions were to include some small charts at the top of the screen inside of the tiles, or to perhaps make these tiles act so that when tapped, the viewport will scroll down to the more detailed chart. My interpretation of the feedback was that while we have the detailed information users might want to see, it's less easily accessible on mobile than desktop.

This is something to be aware of for now, but it doesn't need to be immediately addressed.

Desktop view:
<img width="1091" alt="Screen Shot 2021-01-12 at 11 07 33 PM" src="https://user-images.githubusercontent.com/16804460/104794308-9b0ea200-575b-11eb-9294-aee3399098e5.png">

Mobile view:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/16804460/104794350-e9bc3c00-575b-11eb-9f72-93a18e81e1bf.png">

**Comment by paramshah10** [comment]
I have linked the PR that I just made to this issue since it adds functionality for this
