### ISSUE TITLE
Journal Entry and Chat Buttons Overlap on Smaller Screens

### ISSUE THREAD

**Issue by TylerADavis** [paramshah10/VA-dashboard#5]
Normally, the journal entry icon is in the bottom left and the chat button is in the bottom right. However, on smaller screens like mobile devices, these buttons overlap. 

Based on dragging a Chrome window larger and smaller while in responsive mode, my guess is that what's happening is the journal button is a fixed distance from the left side of the screen, and it does not update its position when the sidebar disappears, leading to this issue.

Screenshot from iPhone 12 / iPhone X / moto G4 viewports below:
![moto_g4_top](https://user-images.githubusercontent.com/16804460/105942210-a2636480-6013-11eb-9651-b483ef2a8417.png)

![ip_x_top](https://user-images.githubusercontent.com/16804460/105942220-a68f8200-6013-11eb-8aa3-5b058bd16020.png)

![IMG_9EB975749363-1](https://user-images.githubusercontent.com/16804460/105942153-88c21d00-6013-11eb-8978-0f99ff6b5a22.jpeg)

Desktop (correct behavior):

![image](https://user-images.githubusercontent.com/16804460/105942589-5e249400-6014-11eb-819b-4c4e4738811b.png)

**Comment by paramshah10** [comment]
Thank you for pointing that out! Will fix it asap

**Comment by TylerADavis** [comment]
Just heard that for the first iteration we show to focus groups, it would be better to not include the journal and chat icons. Would it be possible to drop them for now? I'm not sure if doing that would require more work than just commenting the icons out.

Logic here being that the wider group currently isn't planning to include a journaling feature, and they may instead handle chat through the phone's builtin chat app.

**Comment by TylerADavis** [comment]
@paramshah10 Thanks for commenting these out! I'm closing this issue for now.
